###
GET http://localhost:3001/api/realisateurs
 
###
 
GET http://localhost:3001/api/realisateurs/6620050727df937d6a75ba57
 
###
 
POST http://localhost:3001/api/realisateurs
content-type: application/json
 
{
    "nom": "tarik",
    "birthdate": "2024-04-17T12:00:00Z",
    "biography": "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
}
 
###
 
DELETE http://localhost:3001/api/realisateurs/6620050227df937d6a75ba55
 
 
###
PUT http://localhost:3001/api/realisateurs/6620050227df937d6a75ba55
content-type: application/json
 
{
    "nom": "tarik2",
    "birthdate": "2024-04-17T12:00:00Z",
    "biography": "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
}

###  
GET http://localhost:3001/api/seances
 
###
 
GET http://localhost:3001/api/seances/661fa713118c544e0af2d63d
 
###
 
POST http://localhost:3001/api/seances
content-type: application/json
 
{
  "film": {
    "title": "test",
    "releaseYear": 2000,
    "genre": "action",
    "directors": [
      {
        "nom": "tarik",
        "birthdate": "2024-04-17T12:00:00Z",
        "biography": "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
      },
      {
        "nom": "tarik2",
        "birthdate": "2024-04-17T12:00:00Z",
        "biography": "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
      }
    ]
  },
  "date": "2024-04-17T12:00:00Z",
  "time": "12:00",
  "availableSeats": 100
}
 
###
 
DELETE http://localhost:3001/api/seances/661f9d56ca969489782048d3
 
 
###
PUT http://localhost:3001/api/seances/661f8d762357125add97ef6c
content-type: application/json
 
{
  "film": {
    "title": "test",
    "releaseYear": 2000,
    "genre": "action",
    "directors": [
      {
        "nom": "tarik",
        "birthdate": "2024-04-17T12:00:00Z",
        "biography": "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
      },
      {
        "nom": "tarik2",
        "birthdate": "2024-04-17T12:00:00Z",
        "biography": "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
      }
    ]
  },
  "date": "2024-04-17T12:00:00Z",
  "time": "12:00",
  "availableSeats": 100
}

GET http://localhost:3001/api/films
 
###
 
GET http://localhost:3001/api/films/661fa713118c544e0af2d63d
 
###
POST http://localhost:3001/api/films
content-type: application/json
 
{
  "title": "test",
  "releaseYear": 2000,
  "genre": "Action",
  "directors": [
    {
      "name": "tarik1",
      "birthdate": "1978-05-15T00:00:00.000Z",
      "biography": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
    },
    {
      "name": "tarik2",
      "birthdate": "1985-10-20T00:00:00.000Z",
      "biography": "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    }
  ]
}
 
###
DELETE http://localhost:3001/api/films/661f9d56ca969489782048d3
 
 
###
PUT http://localhost:3001/api/films/661f8d762357125add97ef6c
content-type: application/json
 
{
    "titre": "test",
    "realeaseYear": 2024,
    "genre": "action",
    "directors": [
        {
            "nom": "tarik",
            "birthdate": "2024-04-17T12:00:00Z",
            "biography": "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
        }
    ]
}
